### PR TITLE
Update to jupytelite.github that has a new xarray version

### PR DESCRIPTION
**Pull request by thomasjpfan**
The xarray version on `jupyterlite.github.io` is `2023.12.0`.

### CODE REVIEW

**Comment by scottyhq** [comment]
addresses #679

@jhamman @andersy005 I'm currently working with folks at the scientific python developer summit trying to get these Vercel previews to work, I'm not sure who currently has permissions - I requested to be added 
image

**Comment by andersy005** [comment]
thank you for this addition, @thomasjpfan!

**Comment by andersy005** [comment]
> addresses #679
> 
> @jhamman @andersy005 I'm currently working with folks at the scientific python developer summit trying to get these Vercel previews to work, I'm not sure who currently has permissions - I requested to be added image



@scottyhq, i approved the deployment. 

regarding the addition to the team, unfortunately we are on a free tier plan and adding new members isn;t free 

Screenshot 2024-06-04 at 12 33 10

**Comment by scottyhq** [comment]
> unfortunately we are on a free tier plan and adding new members isn;t free 

Bummer. Well all good. who currently has access @andersy005 ? just you? I'm not sure why it's once again asking for authorization? But this seems good to merge from my point of view!

**Review by andersy005 — APPROVED** [review]
This looks great, @thomasjpfan

**Pull request merged**
