### PR TITLE
Add blogpost for Detrending operations with Dask and Xarray

### PR DESCRIPTION
**Pull request by phofl**

### CODE REVIEW

**Comment by phofl** [comment]
Can I inspect the logs for this in some way?

**Comment by dcherian** [comment]
https://xarray-dev-git-fork-phofl-dask-detrending-xarray.vercel.app/blog/dask-detrending

Gah, need to move the images to `public/` the best way is to just look at a previous blogpost for an example of how to do it.

**Comment by phofl** [comment]
Thanks for the link and the tip with the images! I was looking for them but couldn't find them earlier.


I think this needs another approval to update the deployment now

**Comment by phofl** [comment]
This looks good now!

**Comment by phofl** [comment]
I removed the ticks from the title, they weren't rendered properly but aren't important anyway I think, otherwise it looks good now

**Comment by phofl** [comment]
Do you need something from me before we can merge this?

**Comment by scharlottej13** [comment]
@dcherian @phofl jfyi I'm gonna push up a few more small edits here

**Comment by scharlottej13** [comment]
That's all the changes from me!

**Comment by andersy005** [comment]
thank you all for putting this together! 

are there any outstanding changes or updates needed for this PR, or is it ready to be merged?

**Comment by phofl** [comment]
This is ready to get merged

**Pull request merged**
